# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-15 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191115_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='people_joined',
            field=models.ManyToManyField(related_name='people_on_trip', to='myapp.User'),
        ),
    ]
